### ISSUE TITLE
Automation.tracetemplate does not exist

### ISSUE THREAD

**Issue by xream** [douban/ynm3k#1]
$ ./runTests.sh ./sample/alltests.js "/Users/xream/Library/Application Support/iPhone Simulator/6.0/Applications/37FC8883-4C80-4556-A834-9F044005DF9F/test.app"

显示: 
/Applications/Xcode.app/Contents/Developer
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Instruments/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate
Instruments Usage Error : The specified template 'file://localhost/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Instruments/PlugIns/AutomationInstrument.bundle/Contents/Resources/Automation.tracetemplate' does not exist.
instruments, version 4.5 (4523)
usage: instruments [-t template] [-D document] [-l timeLimit] [-i #] [-w device] [[-p pid] | [application [-e variable value] [argument ...]]]

**Comment by guanbo** [comment]
Try this

## xcodePath=`xcode-select -print-path`

.....

## traceTemplate=$(find ${xcodePath%/*} -type f -name "Automation.tracetemplate")

[Full version](https://github.com/guanbo/Mother-May-UI/blob/master/bin/ios/mother.sh)

**Comment by houlianpi** [comment]
Xcode4.5 changed the path. So I will do something changed to cover this changed

**Comment by houlianpi** [comment]
@guanbo  Thank You
