### ISSUE TITLE
录制完毕，提示Instruments Trace Complete (Duration : 96.311073s; Output : /Users/Shared/ynm3k-master/instrumentscli0.trace)

### ISSUE THREAD

**Issue by ptemail** [douban/ynm3k#2]
录制完毕，提示“Instruments Trace Complete (Duration : 96.311073s; Output : /Users/Shared/ynm3k-master/instrumentscli0.trace)”，但是在 /Users/Shared/ynm3k-master/目录下找不到.trace文件

**Comment by houlianpi** [comment]
ynm3k 不支持录制功能。 而且，我认为你使用方法有问题。好好看看文档吧。

**Comment by ptemail** [comment]
您好：
      非常感谢你的回复！
      我没有用ynm3k录制，只是按照Readme.txt中提供的方式，运行了一下应用程序
     我的疑问是：
     在打开的模拟器中进行操作以后，关闭模拟器，提示生成了instrumentscli0.trace，如：
      Instruments Trace Complete (Duration : 96.311073s; Output : /Users/Shared/ynm3k-master/instrumentscli0.trace
      但是在目录中找不到这个文件。
      ynm3k没有录制功能，是可以对实现脚本进行回放操作，并且生成trace文件，不知道我的理解对不对，目前网上能够收集到的资料很少，不知道是否有编写回放脚本的规范、函数说明这些资料。
       万分感谢你的回复！

在 2012-11-30 15:58:49，mijun notifications@github.com 写道：

ynm3k 不支持录制功能。 而且，我认为你使用方法有问题。好好看看文档吧。

**Comment by houlianpi** [comment]
在打开的模拟器中进行操作以后，关闭模拟器，提示生成了instrumentscli0.trace，
这个在运行完成以后，自动删除了。在runTest的那个文件里面，你可以看一下。
