### ISSUE TITLE
sample folder is missing, so could you update the readme?

### ISSUE THREAD

**Issue by zhaoyingx** [douban/ynm3k#7]
hi ,mijun
Now the readme file is out of sync with the code, so could you update the readme file?And it's better to give us some example to show how to run test case.

Thanks~~

**Comment by dengwei729** [comment]
呵呵，这个东西已经很久没有维护了

**Comment by zhaoyingx** [comment]
@dengwei729  了解，我之前已经试用过了，我的问题也已经解决了，谢谢你的回复：-）
